minimum_pre_commit_version: '3.2.0'
default_language_version:
  python: python3
ci:
  autoupdate_branch: develop
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '(\.(csv|tsv)$|^setup\.cfg$)'

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-eval
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff-check
        args: [--config, code/pyproject.toml, --fix]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        args: [--config, code/pyproject.toml]
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
