name: lint

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Set up Python
      id: setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Lint using pre-commit
      id:  pre-commit
      uses: pre-commit/action@v3.0.0
