name: memote

on:
  push:
    branches:
    - main

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Set up Python
      id: setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      id: install-deps
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install memote==0.16.1
    - name: Run memote on deployment branch
      id: run-memote
      env:
        HEAD_REF: ${{ github.ref_name }}
      run: ./.github/scripts/ghactions_deploy.sh
